# "service" is the name of this project. This will also be added to your AWS resource names.
service: koreanslangquiz
frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-2
  environment:
    HUGGING_FACE_API_TOKEN: ${env:HUGGING_FACE_API_TOKEN}

functions:
  app:
    handler: index.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true # CORS 활성화
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

plugins:
  - serverless-offline # 로컬에서 Lambda를 테스트할 수 있는 플러그인

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**
    - README.md
    - .env