service: korean-slang-quiz-backend

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-2 # AWS 리전, 필요에 따라 변경하세요.
  environment:
    HUGGING_FACE_API_TOKEN: ${env:HUGGING_FACE_API_TOKEN} # Hugging Face API 키 환경 변수 설정

functions:
  app:
    handler: index.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

# plugins:
#   - serverless-offline # 로컬 테스트를 위한 플러그인 (Optional)

package:
  exclude:
    - venv/**
    - .gitignore
    - .git/**
    - README.md
    - aws/
    - awscliv2.zip

